### ISSUE TITLE
[main] Semantically out of place Logo prop

### ISSUE THREAD

**Issue by feychou** [kununu/nukleus#37]
One prop in `Logo` is called `pendingRequests` and we need it to determine whether the flower icon is spinning or not.

It has been pointed out that:

- we do not need the specific number of requests in the `Logo` context, so it may as well be a boolean (it's currently a number);
- we do not need to be so specific with the naming because there may be potentially other actions triggering the animation, so the name `pendingRequests` is not semantically ideal - we could call it `isSpinning` or something on this line.

I am planning to integrate these changes soon in case nobody is contrary.

**Comment by feychou** [comment]
@kaytcat @karlhorky @FreaKzero @clopes-ventureoak

**Comment by karlhorky** [comment]
It's a nice improvement, but I would focus on the bigger architectural things first. Make a JIRA ticket for this please.

**Comment by feychou** [comment]
@karlhorky Closed by mistake, I did not think about doing this within kununu's timeframe.

**Comment by feychou** [comment]
Logo is out of nukleus so we do not need this anymore.
