### ISSUE TITLE
[main] New components

### ISSUE THREAD

**Issue by kaytcat** [kununu/nukleus#4]
These are the components I could come up with:
- [x] Textarea
- [x] InteractiveStars (maybe we can just use Stars with [composition](https://facebook.github.io/react/docs/composition-vs-inheritance.html#specialization) to create a more specialised component)?
- [x] Choice (with radio buttons and blocks)
- [x] MultipleChoice (could embed checkbox group)
- [x] AutocompleteWrapper (Use react-autosuggest with generic container)
- [x] Button

This is what <b>Choice</b> and <b>MultipleChoice</b> are respectively:

<img width="680" alt="screen shot 2016-09-28 at 10 27 29" src="https://cloud.githubusercontent.com/assets/1609297/18906124/87bdb9d2-8566-11e6-8fe1-9ca109a1f4e6.png">

<img width="637" alt="screen shot 2016-09-28 at 10 27 37" src="https://cloud.githubusercontent.com/assets/1609297/18906130/8e80c2b4-8566-11e6-92f9-8ece84fcff8b.png">

@karlhorky @kaytcat @FreaKzero What do you think? Would you add/remove/change something?

**Comment by kaytcat** [comment]
I added the GenericAutocomplete here instead of reusing the admin's CompanyAutocomplete component to make things more reusable. Here is an example of how the container should look.

**Comment by kaytcat** [comment]
@feychou : labels all same size
both choice and radio button should be there
improvement for the new company mode: closing buttom, warning below the first input
title of the review be an input

**Comment by kaytcat** [comment]
@karlhorky : Do we also need a footer here? We have a different footer on the www.kununu.com page as in the admin.

**Comment by feychou** [comment]
I'd say the footer and header are application-specific and we do not need them in the framework.

**Comment by karlhorky** [comment]
Sorry, just saw this question now. I suppose `<Header />` and `<Footer />` belong as customizable elements in order to deliver our styles for them (header: black-ish background color, logo on the left, area for navigation items on the right), while still allowing customizability for the clients.

So something like this:

```js
import {Header} from 'nukleus';

return (
  <Header> // provides bg styling + padding + logo on left
    <nav>
      <ul>
        <li><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
    </nav>
  </Header>
);
```

**Comment by feychou** [comment]
@karlhorky Sounds like a viable thing to do; I am just not sure how easy/possible it is to abstract the styles of such components from the hosting application.

**Comment by karlhorky** [comment]
Not sure I understand. What do you mean about styling things in the header? The way I was imagining, the `<Header />` component provides all of the styles for the header and takes children in to be displayed where children are displayed (floating to the right currently). There would be no customization of the styles - just addition of content.

**Comment by karlhorky** [comment]
In the case that you wanted to style your content somehow, you would create your own component for this:

```js
import {Footer} from 'nukleus';
import {FooterNav} from 'components/FooterNav';

return (
  <Footer> // provides bg styling + padding + children styling + logo on right
    <FooterNav>
  </Footer>
);
```

**Comment by feychou** [comment]
Simply put, if an element can take any style and accept any children and defining a default for it does not cover at least a large percentage of the possible usage, then I see no point in having it in a framework since it's application specific and its existence in the framework may cause more headache (overwriting possible default style, correcting positioning etc.) than benefit.

Anyway, if you want to create a PR for these two elements, feel free ^^ We can bring other people into this discussion and decide together.

**Comment by karlhorky** [comment]
Ah, yeah maybe that's a misunderstanding then. I think the base styling would cover most or all of the use cases for the header or footer (across all applications). You don't think so?

I guess in the admin we may need a `light` theme.

```js
import {Header} from 'nukleus';

return (
  <Header theme="light"> // provides bg styling + padding + children styling + logo on left
    <nav>
      <ul>
        <li><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
    </nav>
  </Header>
);
```

**Comment by karlhorky** [comment]
But yeah, I don't feel too strongly about this. This is your baby @feychou and @kaytcat , so do what feels right.
